Using cuda
Traceback (most recent call last):
  File "C:\Users\Codeexia\FinalSemester\Thesis\practice\AI_project\pytorchforaudio\sound_classification_CNN\train.py", line 85, in <module>
    dataset = ESC50Dataset(
  File "C:\Users\Codeexia\FinalSemester\Thesis\practice\AI_project\pytorchforaudio\sound_classification_CNN\urbansounddataset.py", line 10, in __init__
    self.annotations = pd.read_csv(annotations_file)
  File "C:\Users\Codeexia\FinalSemester\Thesis\practice\.venv\lib\site-packages\pandas\io\parsers\readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\Codeexia\FinalSemester\Thesis\practice\.venv\lib\site-packages\pandas\io\parsers\readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\Users\Codeexia\FinalSemester\Thesis\practice\.venv\lib\site-packages\pandas\io\parsers\readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "C:\Users\Codeexia\FinalSemester\Thesis\practice\.venv\lib\site-packages\pandas\io\parsers\readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "C:\Users\Codeexia\FinalSemester\Thesis\practice\.venv\lib\site-packages\pandas\io\common.py", line 873, in get_handle
    handle = open(
PermissionError: [Errno 13] Permission denied: 'C:/Users/Codeexia/FinalSemester/Thesis/practice/AI_project/pytorchforaudio/sound_classification_CNN/ESC-50-master/meta'
