{"time":"2025-01-16T12:27:44.5384925+01:00","level":"INFO","msg":"stream: starting","core version":"0.19.2","symlink path":"C:\\Users\\Codeexia\\FinalSemester\\Thesis\\practice\\AI_project\\pytorchforaudio\\sound_classification_CNN\\wandb\\run-20250116_122744-rtn3drti\\logs\\debug-core.log"}
{"time":"2025-01-16T12:27:45.8155261+01:00","level":"INFO","msg":"created new stream","id":"rtn3drti"}
{"time":"2025-01-16T12:27:45.8155261+01:00","level":"INFO","msg":"stream: started","id":"rtn3drti"}
{"time":"2025-01-16T12:27:45.8155261+01:00","level":"INFO","msg":"writer: Do: started","stream_id":"rtn3drti"}
{"time":"2025-01-16T12:27:45.8155261+01:00","level":"INFO","msg":"sender: started","stream_id":"rtn3drti"}
{"time":"2025-01-16T12:27:45.8155261+01:00","level":"INFO","msg":"handler: started","stream_id":"rtn3drti"}
{"time":"2025-01-16T12:28:09.9873+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": EOF"}
{"time":"2025-01-16T12:28:22.6653908+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": unexpected EOF"}
{"time":"2025-01-16T12:28:33.3948939+01:00","level":"INFO","msg":"Starting system monitor"}
{"time":"2025-01-16T12:28:34.8143097+01:00","level":"INFO","msg":"stream: closing","id":"rtn3drti"}
{"time":"2025-01-16T12:28:34.8148387+01:00","level":"INFO","msg":"Stopping system monitor"}
{"time":"2025-01-16T12:28:34.8154394+01:00","level":"INFO","msg":"Stopped system monitor"}
{"time":"2025-01-16T12:29:00.4054795+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/codeexia0/esc50_urban_classification/rtn3drti/file_stream\": unexpected EOF"}
{"time":"2025-01-16T12:29:03.4261796+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": read tcp 172.20.10.2:64314->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-01-16T12:29:03.4261796+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": read tcp 172.20.10.2:64314->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
